### PR TITLE
Upgrade Admob to 6.12.2 and added arm64 support

### PR DESCRIPTION
**Pull request by obigu**
Updates AdMob to 6.12.2  (it gets rid of the annoying Google log line about iOS 8 compatibility that was still happening with 6.12.0) and adds arm64 support.

There's some other changes to fix the Xcode project build (had some errors and warnings in Xcode 6). Now, just by going to Product --> Build it should build the library with no errors and runnable on the defined valid architectures armv7, arm64 and i386. (armv7s is "deprecated" on Xcode 6)

Also, there's some git references in the Xcode source control file that are pointing to this repository but that is handled automatically by XCode and should update to any repo the project is cloned from.

### CODE REVIEW

**Comment by dzungpv** [comment]
You copy wrong libadmob.a, it must from Debug-universal and size more than 10mb

**Comment by obigu** [comment]
Fixed now, thanks

**Comment by BlueRiverInteractive** [comment]
Hi thanks for the pull request! Can you please fix the merge conflicts?

**Comment by obigu** [comment]
Ups! I've just realised you updated the project recently and the starting point for this PR was before that refactor making it unmergeable ¬¬. Updating to 6.12.2 from current Master should be trivial. Closing it.

**Pull request closed without merging**
