### PR TITLE
Everyplay

### PR DESCRIPTION
**Pull request by obigu**
New Everyplay bindings for iOS custom engine version 1.9.4.

WARNING: There's a known issue. The EveryplayDelegate is never called, no matter how it's set or referenced. This is quite an important bug not to merge the PR but I'm stuck there. Hopefully somebody will find a way to fix it.

### CODE REVIEW

**Comment by BlueRiverInteractive** [comment]
Hi thanks for the PR. The EveryplayDelegate needs to be strongly referenced. This is done automatically for the property setter `setEveryplayDelegate()` via `strongRef="true"` but needs to be manually done for the initialization methods.

Here's an example for the first init method:

```Java
@Method(selector = "initWithDelegate:")
private static native Everyplay initWithDelegate(EveryplayDelegate everyplayDelegate);

public static Everyplay init(EveryplayDelegate everyplayDelegate) {
    Everyplay result = initWithDelegate(everyplayDelegate);
    result.addStrongRef(everyplayDelegate);
    return result;
}
```

**Comment by obigu** [comment]
Unfortunately I already had done that test and it's not working either. I will commit the change anyway because it's how it should be done but the problem persists...

**Comment by BlueRiverInteractive** [comment]
I've spot another issue. The first two delegate methods `everyplayShown` and `everyplayHidden` are required methods, while the rest is `@optional`. These required methods need a special annotation in the adapter class. You can see how it is done here: 
https://github.com/robovm/robovm/blob/master/cocoatouch/src/main/java/org/robovm/apple/uikit/NSLayoutManagerDelegateAdapter.java

For example:
```Java
@NotImplemented("everyplayShown")
public void shown() {
   throw new UnsupportedOperationException();
}
```
When using the delegate adapter, these two methods need to be overriden without calling super.

BTW you can remove the `everyplay` prefix of all those delegate methods for readability. It should be enough if they are called `shown`, `hidden` and so on.

**Comment by obigu** [comment]
Thank you BlueRiver. Made the suggested changes but still delegate methods are not called :(

**Comment by MonsterOfCookie** [comment]
Hey. 

Did any more progress happen on this? Or is it still in same state?

**Comment by obigu** [comment]
Same state, good news is that the Delegate is not required for integration in most cases. In the examples it's used to call mergeData() in the onStopRecording() but actually, that can be called at any time after start recording.

It would be great to understand why the Delegate is not being called anyway so that we can merge it to master.

**Comment by BlueRiverInteractive** [comment]
I'll merge this now. We can fix the delegate when necessary.

**Pull request merged**
